# Generated by Django 6.0.1 on 2026-02-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chuoicuahang',
            name='icon_map',
            field=models.ImageField(blank=True, null=True, upload_to='chuoi/icon_map/', verbose_name='Icon bản đồ (Leaflet)'),
        ),
        migrations.AddField(
            model_name='chuoicuahang',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chuoi/logo/', verbose_name='Logo chuỗi'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='sanpham/', verbose_name='Hình ảnh sản phẩm'),
        ),
    ]
