# Generated by Django 6.0.1 on 2026-02-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0002_chuoicuahang_icon_map_chuoicuahang_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chuoicuahang',
            name='icon_map',
        ),
    ]
