# Generated by Django 6.0.1 on 2026-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0003_remove_chuoicuahang_icon_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default-avatar.png', null=True, upload_to='nhanvien/', verbose_name='Ảnh nhân viên'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
    ]
