# Generated by Django 6.0.1 on 2026-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0004_nhanvien_avatar_nhanvien_dia_chi_nhanvien_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuoicuahang',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo chuỗi'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', null=True, upload_to='avatar/', verbose_name='Ảnh nhân viên'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình ảnh sản phẩm'),
        ),
    ]
