# Generated by Django 6.0.1 on 2026-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0005_alter_chuoicuahang_logo_alter_nhanvien_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuoicuahang',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/', verbose_name='Logo chuỗi'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/default.png', null=True, upload_to='media/avatar/', verbose_name='Ảnh nhân viên'),
        ),
    ]
