# Generated by Django 6.0.1 on 2026-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0007_alter_nhanvien_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuoicuahang',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo chuỗi'),
        ),
    ]
