# Generated by Django 6.0.1 on 2026-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0008_alter_chuoicuahang_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='avartar/default.png', null=True, upload_to='avartar/', verbose_name='Ảnh nhân viên'),
        ),
    ]
