# Generated by Django 6.0.1 on 2026-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0009_alter_nhanvien_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.png', null=True, upload_to='avatar/', verbose_name='Ảnh nhân viên'),
        ),
    ]
