# Generated by Django 5.2.10 on 2026-02-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0010_alter_nhanvien_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuahang',
            name='dong_cua',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ đóng cửa'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='hoat_dong_24h',
            field=models.BooleanField(default=False, verbose_name='Hoạt động 24h'),
        ),
        migrations.AddField(
            model_name='cuahang',
            name='mo_cua',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ mở cửa'),
        ),
    ]
