# Generated by Django 6.0.2 on 2026-03-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0012_alter_nhanvien_avatar'),
        ('gis_store', '0012_alter_nhanvien_avatar_default_jpg'),
    ]

    operations = [
    ]
