# Generated by Django 6.0.2 on 2026-03-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0013_merge_20260304_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/', verbose_name='Ảnh nhân viên'),
        ),
    ]
