# Generated by Codex on 2026-03-21
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gis_store", "0014_alter_nhanvien_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.CharField(default="error", max_length=20, verbose_name="Mức độ")),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("message", models.TextField(blank=True, verbose_name="Nội dung")),
                ("path", models.CharField(blank=True, max_length=255, verbose_name="Đường dẫn")),
                ("method", models.CharField(blank=True, max_length=10, verbose_name="Phương thức")),
                ("status_code", models.IntegerField(blank=True, null=True, verbose_name="Mã lỗi")),
                ("resolved", models.BooleanField(default=False, verbose_name="Đã xử lý")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Thời gian")),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo",
                "ordering": ["-created_at"],
            },
        ),
    ]
