# Generated by Django 6.0.3 on 2026-03-29 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0016_donhang_chitietdonhang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='don_gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn giá'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='gia_ban',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá bán'),
        ),
        migrations.CreateModel(
            name='HoSoKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('dia_chi', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ho_so_khach_hang', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Hồ sơ khách hàng',
                'verbose_name_plural': 'Hồ sơ khách hàng',
            },
        ),
    ]
