# Generated by Django 5.2.11 on 2026-03-31 05:56

import modules.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0022_diachikhachhang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100, verbose_name='Model')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Dữ liệu')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian xóa')),
                ('expires_at', models.DateTimeField(default=modules.store.models._trash_expiry, verbose_name='Hết hạn')),
            ],
            options={
                'verbose_name': 'Thùng rác',
                'verbose_name_plural': 'Thùng rác',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
